# Generated by Django 4.2.5 on 2023-10-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='status',
            new_name='completed',
        ),
    ]
